export const GET_CATEGORIES_REQUEST="GET_CATEGORIES_REQUEST";
export const GET_CATEGORIES_SUCCESS="GET_CATEGORIES_SUCCESS";
export const GET_CATEGORIES_FAILURE="GET_CATEGORIES_FAILURE";
export const ADD_CATEGORY_SUCCESS="ADD_CATEGORY_SUCCESS";
export const UPDATE_CATEGORY_SUCCESS="UPDATE_CATEGORY_SUCCESS";
export const DELETE_CATEGORY_SUCCESS="DELETE_CATEGORY_SUCCESS";