export const GET_TEAMS_REQUEST="GET_TEAMS_REQUEST";

export const GET_TEAMS_SUCCESS="GET_TEAMS_SUCCESS";

export const GET_TEAMS_FAILURE="GET_TEAMS_FAILURE";
export const ADD_TEAM_SUCCESS="ADD_TEAM_SUCCESS";
export const UPDATE_TEAM_SUCCESS="UPDATE_TEAM_SUCCESS";
export const DELETE_TEAM_SUCCESS="DELETE_TEAM_SUCCESS";