export const GET_CATALOGS_REQUEST="GET_CATALOGS_REQUEST";
export const GET_CATALOGS_SUCCESS="GET_CATALOGS_SUCCESS";
export const GET_CATALOGS_FAILURE="GET_CATALOGS_FAILURE";
export const ADD_CATALOG_SUCCESS="ADD_CATALOG_SUCCESS";
export const UPDATE_CATALOG_SUCCESS="UPDATE_CATALOG_SUCCESS";
export const DELETE_CATALOG_SUCCESS="DELETE_CATALOG_SUCCESS";
export const DOWNLOAD_CATALOG_SUCCESS="DOWNLOAD_CATALOG_SUCCESS";

