export const GET_ABOUTS_REQUEST="GET_ABOUTS_REQUEST";
export const GET_ABOUTS_SUCCESS="GET_ABOUTS_SUCCESS";
export const GET_ABOUTS_FAILURE="GET_ABOUTS_FAILURE";
export const UPDATE_ABOUT_SUCCESS='UPDATE_ABOUT_SUCCESS'