export const GET_PROPERTIES_REQUEST="GET_PROPERTIES_REQUEST";

export const GET_PROPERTIES_SUCCESS="GET_PROPERTIES_SUCCESS";

export const GET_PROPERTIES_FAILURE="GET_PROPERTIES_FAILURE";

export const ADD_PROPERTY_SUCCESS="ADD_PROPERTY_SUCCESS";

export const UPDATE_PROPERTY_SUCCESS="UPDATE_PROPERTY_SUCCESS";

export const DELETE_PROPERTY_SUCCESS="DELETE_PROPERTY_SUCCESS";