export const GET_SECTORS_REQUEST="GET_SECTORS_REQUEST";
export const GET_SECTORS_SUCCESS="GET_SECTORS_SUCCESS";
export const GET_SECTORS_FAILURE="GET_SECTORS_FAILURE";
export const ADD_SECTOR_SUCCESS="ADD_SECTOR_SUCCESS";
export const UPDATE_SECTOR_SUCCESS="UPDATE_SECTOR_SUCCESS";
export const DELETE_SECTOR_SUCCESS="DELETE_SECTOR_SUCCESS";