export const GET_MODELS_REQUEST="GET_MODELS_REQUEST";

export const GET_MODELS_SUCCESS="GET_MODELS_SUCCESS";

export const GET_MODELS_FAILURE="GET_MODELS_FAILURE";

export const ADD_MODEL_SUCCESS="ADD_MODEL_SUCCESS";

export const UPDATE_MODEL_SUCCESS="UPDATE_MODEL_SUCCESS";

export const DELETE_MODEL_SUCCESS="DELETE_MODEL_SUCCESS";