export const GET_SERVICES_REQUEST="GET_SERVICES_REQUEST";
export const GET_SERVICES_SUCCESS="GET_SERVICES_SUCCESS";
export const GET_SERVICES_FAILURE="GET_SERVICES_FAILURE";
export const ADD_SERVICE_SUCCESS="ADD_SERVICE_SUCCESS";
export const UPDATE_SERVICE_SUCCESS="UPDATE_SERVICE_SUCCESS";
export const DELETE_SERVICE_SUCCESS="DELETE_SERVICE_SUCCESS";