export const GET_QUALITIES_REQUEST="GET_QUALITIES_REQUEST";

export const GET_QUALITIES_SUCCESS="GET_QUALITIES_SUCCESS";

export const GET_QUALITIES_FAILURE="GET_QUALITIES_FAILURE";

export const ADD_QUALITY_SUCCESS="ADD_QUALITY_SUCCESS";

export const UPDATE_QUALITY_SUCCESS="UPDATE_QUALITY_SUCCESS";

export const DELETE_QUALITY_SUCCESS="DELETE_QUALITY_SUCCESS";
