export const GET_PRODUCTS_REQUEST="GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_SUCCESS="GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAILURE="GET_PRODUCTS_FAILURE";
export const ADD_PRODUCT_SUCCESS="ADD_PRODUCT_SUCCESS";

export const UPDATE_PRODUCT_SUCCESS="UPDATE_PRODUCT_SUCCESS";

export const DELETE_PRODUCT_SUCCESS="DELETE_PRODUCT_SUCCESS";