export const GET_USERS_REQUEST="GET_USERS_REQUEST";
export const GET_USERS_SUCCESS="GET_USERS_SUCCESS";
export const GET_USERS_FAILURE="GET_USERS_FAILURE";
export const ADD_USER_SUCCESS="ADD_USER_SUCCESS";
export const UPDATE_USER_SUCCESS="ADD_USER_SUCCESS";
export const DELETE_USER_SUCCESS="DELETE_USER_SUCCESS";

